import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faHome,
  faInfo,
  faUser,
  faSignInAlt,
  faSignOutAlt,
  faEdit,
  faChartLine,
  faDollarSign,
  faFire,
  faCoins,
  faBars,
  faTimes,
  faChartPie,
  faUserCircle,
  faWallet,
  faXmark,
  faShield,
  faUsers,
  faUserTag,
  faEnvelope,
  faTrash,
  faHashtag,
  faWrench,
  faUserPen,
  faCheckCircle,
  faTriangleExclamation,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faHome,
  faInfo,
  faUser,
  faSignInAlt,
  faSignOutAlt,
  faEdit,
  faChartLine,
  faDollarSign,
  faFire,
  faCoins,
  faBars,
  faTimes,
  faChartPie,
  faUserCircle,
  faWallet,
  faXmark,
  faShield,
  faUsers,
  faUserTag,
  faEnvelope,
  faTrash,
  faHashtag,
  faWrench,
  faUserPen,
  faCheckCircle,
  faTriangleExclamation,
)

export { FontAwesomeIcon }
